### ISSUE TITLE
Disable logging on test suit

### ISSUE THREAD

**Issue by lerrua** [henriquebastos/sqlformatter#2]
@henriquebastos great work, man!

I have a question about it, Is it possible to disable logging when i'm running tests? (I'm using django+pytest)
It's very uncomfortable seeing the a lot of outputs when the database is created.

Thanks!

**Comment by henriquebastos** [comment]
If you have a setup script on pytest you can globally disable the logs. [Check out how](http://stackoverflow.com/questions/5255657/how-can-i-disable-logging-while-running-unit-tests-in-python-django).
