### ISSUE TITLE
Can SQLFormatter be used to format Messy SQL code?

### ISSUE THREAD

**Issue by dclong** [henriquebastos/sqlformatter#6]
Say that I have a file containing messy SQL code. Can I use SQLFormatter to format the SQL code?

**Comment by henriquebastos** [comment]
I don't know. Never tested that. I think sqlformatter would work well for a
single query.

To reformat code, I would use an IDE or something like that.

Em 11 de set de 2017 3:11 AM, "Ben Chuanlong Du" <notifications@github.com>
escreveu:
